//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anagrafico_Impianti
    {
        public string ID_PLant { get; set; }
        public string Desc_Plant { get; set; }
        public System.DateTime DT_Install_Plant { get; set; }
        public Nullable<int> Costo_Plant { get; set; }
        public string Azienda { get; set; }
        public string Divisione { get; set; }
        public string CDC_Plant { get; set; }
        public string Tipo_Plant { get; set; }
        public Nullable<int> DT_Lastmaint { get; set; }
        public Nullable<int> DT_Nextmaint { get; set; }
        public string Esito_maint { get; set; }
        public Nullable<int> Grado_risk_plant { get; set; }
        public string Stato { get; set; }
    }
}
