//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anagrafico_Fornitori
    {
        public string ID_PLant { get; set; }
        public string ID_Fornitore { get; set; }
        public string Desc_Fornitore { get; set; }
        public string Indirizzo1 { get; set; }
        public string Indirizzo2 { get; set; }
        public string CDC_Riferimento { get; set; }
        public Nullable<int> Costo_Orario { get; set; }
        public string CityFrazione { get; set; }
        public string Nazione { get; set; }
        public string CAP_Forn { get; set; }
        public Nullable<System.DateTime> DT_Valid_Forn { get; set; }
        public Nullable<System.DateTime> DT_Last_Inter { get; set; }
        public string Stato { get; set; }
    }
}
