//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anagrafico_Interventi
    {
        public string ID_PLant { get; set; }
        public string Desc_Inter { get; set; }
        public Nullable<System.DateTime> DT_Chiamata { get; set; }
        public Nullable<int> Tarif_Inter { get; set; }
        public string Tipo_Risorsa { get; set; }
        public string Desc_Risorsa { get; set; }
        public string CDC_Risorsa { get; set; }
        public string Tipo_Plant { get; set; }
        public Nullable<int> DT_Conf_Int { get; set; }
        public Nullable<int> DT_Eff_Int { get; set; }
        public Nullable<int> DT_Ultimo_Guasto { get; set; }
        public Nullable<int> DT_Ultima_Riparazione { get; set; }
        public string Esito_maint { get; set; }
        public string Stato { get; set; }
        public string ID_Inter { get; set; }
        public string ID_Persona { get; set; }
        public Nullable<int> ORE_Inter { get; set; }
        public Nullable<int> Costo_Inter { get; set; }
        public Nullable<int> Probabil { get; set; }
        public Nullable<int> Gravity { get; set; }
        public Nullable<int> Rilevabil { get; set; }
    }
}
