//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTIVITA
    {
        public string ID_Attivit { get; set; }
        public string Desc_Attivit { get; set; }
        public Nullable<System.DateTime> DT_Inizio_ATT { get; set; }
        public Nullable<System.DateTime> DT_Fine_ATT { get; set; }
        public Nullable<decimal> Valore1_ATT { get; set; }
        public Nullable<decimal> Valore2_ATT { get; set; }
        public Nullable<decimal> Valore3_ATT { get; set; }
        public Nullable<decimal> Valore4_ATT { get; set; }
        public Nullable<decimal> Valore5_ATT { get; set; }
        public Nullable<decimal> Valore6_ATT { get; set; }
        public Nullable<decimal> Valore7_ATT { get; set; }
        public Nullable<decimal> Valore8_ATT { get; set; }
        public Nullable<decimal> Valore9_ATT { get; set; }
        public Nullable<decimal> Valore10_ATT { get; set; }
        public string ID_Persona { get; set; }
        public string ID_Commessa { get; set; }
        public string ID_ORDPROD { get; set; }
        public string ID_CDC { get; set; }
        public string NOTE { get; set; }
        public string Stato { get; set; }
    }
}
