//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autorizzazioni
    {
        public string ID_User { get; set; }
        public Nullable<System.DateTime> DT_Ins_User { get; set; }
        public Nullable<int> LVL_User { get; set; }
        public string Auth_Code { get; set; }
        public Nullable<System.DateTime> DT_End_Auth { get; set; }
    }
}
