//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILLING
    {
        public string ID_USER { get; set; }
        public string DESC_USER { get; set; }
        public System.DateTime DT_ATTIVAZIONE { get; set; }
        public Nullable<System.DateTime> DT_TERMINE { get; set; }
        public Nullable<decimal> TARIFFA { get; set; }
        public string ANNO { get; set; }
        public string MESE { get; set; }
        public Nullable<decimal> GIORNO_INIZIO { get; set; }
        public Nullable<decimal> GIORNO_FINE { get; set; }
        public Nullable<decimal> VALORE { get; set; }
    }
}
