//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTROLLI
    {
        public string ID_Controllo { get; set; }
        public string Desc_Controllo { get; set; }
        public Nullable<System.DateTime> DT_Inizio_Controllo { get; set; }
        public Nullable<System.DateTime> DT_Fine_Controllo { get; set; }
        public Nullable<decimal> Valore1_CTRL { get; set; }
        public Nullable<decimal> Valore2_CTRL { get; set; }
        public Nullable<decimal> Valore3_CTRL { get; set; }
        public Nullable<decimal> Valore4_CTRL { get; set; }
        public Nullable<decimal> Valore5_CTRL { get; set; }
        public Nullable<decimal> Valore6_CTRL { get; set; }
        public Nullable<decimal> Valore7_CTRL { get; set; }
        public Nullable<decimal> Valore8_CTRL { get; set; }
        public Nullable<decimal> Valore9_CTRL { get; set; }
        public Nullable<decimal> Valore10_CTRL { get; set; }
        public string ID_Persona { get; set; }
        public string ID_Commessa { get; set; }
        public string ID_ORDPROD { get; set; }
        public string ID_CDC { get; set; }
        public string NOTE { get; set; }
        public string Stato { get; set; }
    }
}
