//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interfaccie
    {
        public string SISTEMA { get; set; }
        public Nullable<System.DateTime> DT_Attivazione { get; set; }
        public Nullable<System.DateTime> Dt_disattivazione { get; set; }
        public string Auth_Code { get; set; }
        public string Parametri1 { get; set; }
        public string Parametri2 { get; set; }
        public string Parametri3 { get; set; }
        public string Host_abilitato { get; set; }
        public string IP_Host_Abilitato { get; set; }
        public Nullable<decimal> IPV4_IPV6 { get; set; }
        public string Stato { get; set; }
    }
}
