//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materiali_Manut
    {
        public string ID_PLant { get; set; }
        public string ID_Mater { get; set; }
        public string Desc_Mater { get; set; }
        public Nullable<int> Codificato { get; set; }
        public string ID_Fornitore { get; set; }
        public Nullable<System.DateTime> DT_Uso__Mater { get; set; }
        public string CDC_Riferimento { get; set; }
        public Nullable<int> Costo_Mater { get; set; }
        public string Stato { get; set; }
    }
}
