//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class STATI
    {
        public string ID_STATO { get; set; }
        public string Desc_Guasto { get; set; }
        public string Stato { get; set; }
    }
}
