//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tst_db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_CONTROLLI
    {
        public string ID_Controllo { get; set; }
        public string Desc_Controllo { get; set; }
        public Nullable<decimal> Soglia_Sup { get; set; }
        public Nullable<decimal> Soglia_Inf { get; set; }
        public Nullable<decimal> Scala_Assoluta { get; set; }
        public string Stato { get; set; }
    }
}
