//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AppLeanMaint.MaintenanceWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MaintenanceSoap", Namespace="http://objlab.it/")]
    public partial class Maintenance : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PingOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateSupplierOperationCompleted;
        
        private System.Threading.SendOrPostCallback SearchAssetOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Maintenance() {
            this.Url = "http://dev1.objlab.it/WS/Maintenance.asmx";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PingCompletedEventHandler PingCompleted;
        
        /// <remarks/>
        public event CreateSupplierCompletedEventHandler CreateSupplierCompleted;
        
        /// <remarks/>
        public event SearchAssetCompletedEventHandler SearchAssetCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://objlab.it/Ping", RequestNamespace="http://objlab.it/", ResponseNamespace="http://objlab.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Ping() {
            object[] results = this.Invoke("Ping", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PingAsync() {
            this.PingAsync(null);
        }
        
        /// <remarks/>
        public void PingAsync(object userState) {
            if ((this.PingOperationCompleted == null)) {
                this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
            }
            this.InvokeAsync("Ping", new object[0], this.PingOperationCompleted, userState);
        }
        
        private void OnPingOperationCompleted(object arg) {
            if ((this.PingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://objlab.it/CreateSupplier", RequestNamespace="http://objlab.it/", ResponseNamespace="http://objlab.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int CreateSupplier(string sUsername, string sPassword, string sName, string sDescription, string sEmail, string sMobile, SupplierTypeEnum eType) {
            object[] results = this.Invoke("CreateSupplier", new object[] {
                        sUsername,
                        sPassword,
                        sName,
                        sDescription,
                        sEmail,
                        sMobile,
                        eType});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CreateSupplierAsync(string sUsername, string sPassword, string sName, string sDescription, string sEmail, string sMobile, SupplierTypeEnum eType) {
            this.CreateSupplierAsync(sUsername, sPassword, sName, sDescription, sEmail, sMobile, eType, null);
        }
        
        /// <remarks/>
        public void CreateSupplierAsync(string sUsername, string sPassword, string sName, string sDescription, string sEmail, string sMobile, SupplierTypeEnum eType, object userState) {
            if ((this.CreateSupplierOperationCompleted == null)) {
                this.CreateSupplierOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSupplierOperationCompleted);
            }
            this.InvokeAsync("CreateSupplier", new object[] {
                        sUsername,
                        sPassword,
                        sName,
                        sDescription,
                        sEmail,
                        sMobile,
                        eType}, this.CreateSupplierOperationCompleted, userState);
        }
        
        private void OnCreateSupplierOperationCompleted(object arg) {
            if ((this.CreateSupplierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSupplierCompleted(this, new CreateSupplierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://objlab.it/SearchAsset", RequestNamespace="http://objlab.it/", ResponseNamespace="http://objlab.it/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Asset[] SearchAsset(string sName) {
            object[] results = this.Invoke("SearchAsset", new object[] {
                        sName});
            return ((Asset[])(results[0]));
        }
        
        /// <remarks/>
        public void SearchAssetAsync(string sName) {
            this.SearchAssetAsync(sName, null);
        }
        
        /// <remarks/>
        public void SearchAssetAsync(string sName, object userState) {
            if ((this.SearchAssetOperationCompleted == null)) {
                this.SearchAssetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSearchAssetOperationCompleted);
            }
            this.InvokeAsync("SearchAsset", new object[] {
                        sName}, this.SearchAssetOperationCompleted, userState);
        }
        
        private void OnSearchAssetOperationCompleted(object arg) {
            if ((this.SearchAssetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SearchAssetCompleted(this, new SearchAssetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://objlab.it/")]
    public enum SupplierTypeEnum {
        
        /// <remarks/>
        Maintenance,
        
        /// <remarks/>
        Producer,
        
        /// <remarks/>
        Consultant,
        
        /// <remarks/>
        Materials,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://objlab.it/")]
    public partial class Asset {
        
        private int iD_AssetField;
        
        private string nameField;
        
        private string descriptionField;
        
        private int iD_AssetTypeField;
        
        private int iD_OrganizationCenterField;
        
        private int iD_CostCenterField;
        
        private int iD_GeographicCenterField;
        
        private bool iD_GeographicCenter_HasValueField;
        
        private int iD_ObjStatusField;
        
        private int iD_ParentField;
        
        private bool iD_Parent_HasValueField;
        
        /// <remarks/>
        public int ID_Asset {
            get {
                return this.iD_AssetField;
            }
            set {
                this.iD_AssetField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int ID_AssetType {
            get {
                return this.iD_AssetTypeField;
            }
            set {
                this.iD_AssetTypeField = value;
            }
        }
        
        /// <remarks/>
        public int ID_OrganizationCenter {
            get {
                return this.iD_OrganizationCenterField;
            }
            set {
                this.iD_OrganizationCenterField = value;
            }
        }
        
        /// <remarks/>
        public int ID_CostCenter {
            get {
                return this.iD_CostCenterField;
            }
            set {
                this.iD_CostCenterField = value;
            }
        }
        
        /// <remarks/>
        public int ID_GeographicCenter {
            get {
                return this.iD_GeographicCenterField;
            }
            set {
                this.iD_GeographicCenterField = value;
            }
        }
        
        /// <remarks/>
        public bool ID_GeographicCenter_HasValue {
            get {
                return this.iD_GeographicCenter_HasValueField;
            }
            set {
                this.iD_GeographicCenter_HasValueField = value;
            }
        }
        
        /// <remarks/>
        public int ID_ObjStatus {
            get {
                return this.iD_ObjStatusField;
            }
            set {
                this.iD_ObjStatusField = value;
            }
        }
        
        /// <remarks/>
        public int ID_Parent {
            get {
                return this.iD_ParentField;
            }
            set {
                this.iD_ParentField = value;
            }
        }
        
        /// <remarks/>
        public bool ID_Parent_HasValue {
            get {
                return this.iD_Parent_HasValueField;
            }
            set {
                this.iD_Parent_HasValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CreateSupplierCompletedEventHandler(object sender, CreateSupplierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateSupplierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateSupplierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SearchAssetCompletedEventHandler(object sender, SearchAssetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SearchAssetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SearchAssetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Asset[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Asset[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591